from flask import Flask, jsonify, send_from_directory, request
from flask_cors import CORS
from sqlalchemy import create_engine, func
from sqlalchemy.orm import sessionmaker
import os
import sys
import time
from threading import Thread
from dotenv import load_dotenv

# Ensure local imports resolve when launched from other working dirs.
sys.path.insert(0, os.path.dirname(__file__))

# Reuse the ORM models defined in LeagueTool.py (no side effects on import).
from LeagueTool import (
    MatchInfoDto, ParticipantDto, TeamDto, LeagueEntryDTO,
    AccountDto, MatchIdDto, FramesTimeLineDto, ParticipantFramesDto, ParticipantFrameDto, ParticipantTimeLineDto,
    RiotApiClient, DatabaseManager, AmadeusPipeline
)

# Path to the SQLite DB generated by LeagueTool.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH  = os.path.join(BASE_DIR, "db", "LeagueToolDb.db")
DB_URL   = f"sqlite:///{DB_PATH}"

# Load .env so RIOT_API_KEY is available when the server triggers the pipeline.
load_dotenv(os.path.join(BASE_DIR, ".env"))

app = Flask(__name__, static_folder='index')
CORS(app)

engine  = create_engine(f'sqlite:///{DB_PATH}')
Session = sessionmaker(bind=engine)

def get_session():
    return Session()

RUN_STATUS = {
    "status": "idle",
    "start_ts": None,
    "end_ts": None,
    "error": None,
    "matches_requested": 0,
    "matches_new": 0,
    "game_name": None,
    "tag_line": None,
    "clear_db": None
}

def get_tracked_puuid(db):
    """Return the most recently stored account puuid (the one pipeline fetched)."""
    account = db.query(AccountDto).order_by(AccountDto.id.desc()).first()
    return account.puuid if account else None

def get_tracked_summoner_id(db, puuid: str):
    """Grab the most recent summonerId for the tracked puuid from participants."""
    participant = (
        db.query(ParticipantDto.summonerId)
        .filter(ParticipantDto.puuid == puuid, ParticipantDto.summonerId != None)
        .order_by(ParticipantDto.id.desc())
        .first()
    )
    return participant[0] if participant else None

# ── Routes ────────────────────────────────────────────────────────────────────

@app.route('/')
def index():
    return send_from_directory(app.static_folder, 'index.html')
@app.route('/api/summary')
def summary():
    """Overall stats: total games, win rate, avg KDA."""
    db = get_session()
    try:
        puuid = get_tracked_puuid(db)
        if not puuid:
            return jsonify({"error": "No tracked account found"})

        participants = db.query(ParticipantDto).filter(ParticipantDto.puuid == puuid).all()
        if not participants:
            return jsonify({"error": "No data found for tracked account"})

        total  = len(participants)
        wins   = sum(1 for p in participants if p.win)
        kills  = sum(p.kills or 0 for p in participants)
        deaths = sum(p.deaths or 0 for p in participants)
        assists= sum(p.assists or 0 for p in participants)

        # Average KDA per game for the tracked player
        avg_kda = round(sum((p.kills or 0 + p.assists or 0) / max(p.deaths or 0, 1) for p in participants) / total, 2)

        return jsonify({
            "total_games": total,
            "wins": wins,
            "losses": total - wins,
            "win_rate": round(wins / total * 100, 1),
            "avg_kills":   round(kills   / total, 1),
            "avg_deaths":  round(deaths  / total, 1),
            "avg_assists": round(assists / total, 1),
            "avg_kda": avg_kda
        })
    finally:
        db.close()

@app.route('/api/champions')
def champions():
    """Per-champion stats: games, wins, avg KDA."""
    db = get_session()
    try:
        puuid = get_tracked_puuid(db)
        if not puuid:
            return jsonify({"error": "No tracked account found"})

        participants = db.query(ParticipantDto).filter(ParticipantDto.puuid == puuid).all()
        champ_data = {}

        for p in participants:
            name = p.championName or "Unknown"
            if name not in champ_data:
                champ_data[name] = {"games": 0, "wins": 0, "kills": 0, "deaths": 0, "assists": 0}
            c = champ_data[name]
            c["games"]   += 1
            c["wins"]    += 1 if p.win else 0
            c["kills"]   += p.kills   or 0
            c["deaths"]  += p.deaths  or 0
            c["assists"] += p.assists or 0

        result = []
        for name, c in champ_data.items():
            g = c["games"]
            kda = round((c["kills"] + c["assists"]) / max(c["deaths"], 1), 2)
            result.append({
                "champion":  name,
                "games":     g,
                "wins":      c["wins"],
                "win_rate":  round(c["wins"] / g * 100, 1),
                "avg_kills":   round(c["kills"]   / g, 1),
                "avg_deaths":  round(c["deaths"]  / g, 1),
                "avg_assists": round(c["assists"] / g, 1),
                "kda": kda
            })

        result.sort(key=lambda x: x["games"], reverse=True)
        return jsonify(result)
    finally:
        db.close()

@app.route('/api/recent')
def recent():
    """Last 10 matches with basic info."""
    db = get_session()
    try:
        infos = db.query(MatchInfoDto).order_by(MatchInfoDto.gameCreation.desc()).limit(10).all()
        puuid = get_tracked_puuid(db)
        if not puuid:
            return jsonify({"error": "No tracked account found"})
        result = []
        for info in infos:
            target = next((p for p in info.participants if p.puuid == puuid), None)
            if not target and info.participants:
                target = info.participants[0]  # fallback
            if not target:
                continue
            result.append({
                "match_id":      info.gameId,
                "champion":      target.championName,
                "win":           target.win,
                "kills":         target.kills,
                "deaths":        target.deaths,
                "assists":       target.assists,
                "cs":            (target.totalMinionsKilled or 0) + (target.neutralMinionsKilled or 0),
                "vision_score":  target.visionScore,
                "game_duration": info.gameDuration,
                "game_mode":     info.gameMode,
                "map_id":        info.mapId,
                "queue_id":      info.queueId,
            })
        return jsonify(result)
    finally:
        db.close()

@app.route('/api/rank')
def rank():
    """Current ranked standing."""
    db = get_session()
    try:
        entries = db.query(LeagueEntryDTO).all()
        result  = []
        for e in entries:
            result.append({
                "queue":   e.queueType,
                "tier":    e.tier,
                "rank":    e.rank,
                "lp":      e.leaguePoints,
                "wins":    e.wins,
                "losses":  e.losses,
                "win_rate": round(e.wins / max(e.wins + e.losses, 1) * 100, 1),
                "hot_streak": e.hotStreak,
                "veteran":    e.veteran,
                "fresh_blood": e.freshBlood,
            })
        return jsonify(result)
    finally:
        db.close()

@app.route('/api/gold_timeline')
def gold_timeline():
    """Average gold per minute across all games."""
    db = get_session()
    try:
        puuid = get_tracked_puuid(db)
        if not puuid:
            return jsonify({"error": "No tracked account found"})

        # Map each timeline info_id to the tracked participantId
        tracked_participants = {
            pt.info_id: pt.participantId
            for pt in db.query(ParticipantTimeLineDto).filter(ParticipantTimeLineDto.puuid == puuid).all()
        }

        frames = db.query(FramesTimeLineDto)\
            .filter(FramesTimeLineDto.info_id.in_(tracked_participants.keys()))\
            .order_by(FramesTimeLineDto.timestamp)\
            .all()

        timeline = {}
        for frame in frames:
            minute = frame.timestamp // 60000
            if not frame.participant_frames:
                continue
            for pf in frame.participant_frames.participant_data:
                if tracked_participants.get(frame.info_id) != pf.participantId:
                    continue
                if minute not in timeline:
                    timeline[minute] = {"gold": 0, "count": 0}
                timeline[minute]["gold"]  += pf.totalGold or 0
                timeline[minute]["count"] += 1

        result = [
            {"minute": m, "avg_gold": round(timeline[m]["gold"] / timeline[m]["count"])}
            for m in sorted(timeline.keys())
            if timeline[m]["count"] > 0
        ]
        return jsonify(result)
    finally:
        db.close()

# ── Run ───────────────────────────────────────────────────────────────────────

@app.route('/api/run', methods=['POST'])
def run_pipeline():
    """Kick off a background refresh of the DB for a given summoner."""
    payload = request.get_json(force=True, silent=True) or {}
    game_name   = (payload.get("game_name") or "").strip()
    tag_line    = (payload.get("tag_line") or "").strip()
    # default match count from env or 20
    env_default_mc = os.getenv("AMADEUS_MATCH_COUNT_DEFAULT")
    try:
        env_default_mc = int(env_default_mc) if env_default_mc is not None else 20
    except ValueError:
        env_default_mc = 20
    match_count = payload.get("match_count", env_default_mc)

    clear_db    = payload.get("clear_db", None)
    rate_limit_env = os.getenv("AMADEUS_RATE_LIMIT_SLEEP", "1.5")
    try:
        rate_limit_sleep = float(rate_limit_env)
    except ValueError:
        rate_limit_sleep = 1.5

    try:
        match_count = max(1, min(50, int(match_count)))
    except (TypeError, ValueError):
        return jsonify({"error": "match_count must be an integer"}), 400

    if not game_name or not tag_line:
        return jsonify({"error": "game_name and tag_line are required"}), 400

    api_key = os.getenv("RIOT_API_KEY")
    if not api_key:
        return jsonify({"error": "RIOT_API_KEY missing on server"}), 500

    def to_bool(val):
        if isinstance(val, bool):
            return val
        if val is None:
            return None
        return str(val).lower() in ("1", "true", "yes", "y")

    clear_flag = to_bool(clear_db)

    def task():
        try:
            api = RiotApiClient(api_key=api_key)
            db  = DatabaseManager(db_url=DB_URL, clear_on_init=clear_flag)
            pipeline = AmadeusPipeline(api_client=api, db_manager=db, rate_limit_sleep=rate_limit_sleep)
            stats = pipeline.run(game_name=game_name, tag_line=tag_line, match_count=match_count)
            RUN_STATUS.update({
                "status": "success",
                "end_ts": time.time(),
                "matches_requested": stats.get("matches_requested", 0),
                "matches_new": stats.get("matches_new", 0),
                "error": None
            })
            print(f"[run] Completed pipeline for {game_name}#{tag_line}")
        except Exception as exc:
            print(f"[run] Pipeline failed: {exc}", file=sys.stderr)
            RUN_STATUS.update({
                "status": "error",
                "end_ts": time.time(),
                "error": str(exc)
            })

    RUN_STATUS.update({
        "status": "running",
        "start_ts": time.time(),
        "end_ts": None,
        "error": None,
        "matches_requested": 0,
        "matches_new": 0,
        "game_name": game_name,
        "tag_line": tag_line,
        "clear_db": bool(clear_flag) if clear_flag is not None else None
    })
    Thread(target=task, daemon=True).start()
    return jsonify({
        "status": "started",
        "game_name": game_name,
        "tag_line": tag_line,
        "match_count": match_count,
        "clear_db": bool(clear_flag) if clear_flag is not None else None,
        "rate_limit_sleep": rate_limit_sleep
    })

@app.route('/api/run/status')
def run_status():
    """Return last pipeline run status."""
    return jsonify(RUN_STATUS)

@app.route('/api/active_game')
def active_game():
    """Check if tracked player is currently in an active game (Spectator API)."""
    api_key = os.getenv("RIOT_API_KEY")
    if not api_key:
        return jsonify({"error": "RIOT_API_KEY missing on server"}), 500

    db = get_session()
    try:
        puuid = get_tracked_puuid(db)
        if not puuid:
            return jsonify({"error": "No tracked account found"}), 404
        summoner_id = get_tracked_summoner_id(db, puuid)
        if not summoner_id:
            return jsonify({"error": "No summonerId available for tracked account"}), 404

        api = RiotApiClient(api_key=api_key)
        try:
            game = api.get_active_game(summoner_id)
        except Exception as exc:
            # 404 from spectator means not in game
            if "404" in str(exc):
                return jsonify({"active": False})
            # propagate other errors
            return jsonify({"error": str(exc)}), 500

        # If no exception, player is in an active game
        return jsonify({
            "active": True,
            "game_mode": game.get("gameMode"),
            "game_type": game.get("gameType"),
            "game_start": game.get("gameStartTime"),
            "map_id": game.get("mapId"),
            "queue_id": game.get("gameQueueConfigId")
        })
    finally:
        db.close()


if __name__ == '__main__':
    print("\nAmadeus is running -> http://localhost:5000\n")
    app.run(debug=True, port=5000)



